KANJI_CARDS = (
    {
        'character': '日',
        'reading': 'ひ / にち',
        'meaning': 'sun; day',
        'level': 'T5',
    },
    {
        'character': '月',
        'reading': 'つき / げつ',
        'meaning': 'moon; month',
        'level': 'T5',
    },
    {
        'character': '火',
        'reading': 'ひ / か',
        'meaning': 'fire',
        'level': 'T5',
    },
    {
        'character': '水',
        'reading': 'みず / すい',
        'meaning': 'water',
        'level': 'T5',
    },
    {
        'character': '木',
        'reading': 'き / もく',
        'meaning': 'tree; wood',
        'level': 'T5',
    },
    {
        'character': '金',
        'reading': 'かね / きん',
        'meaning': 'gold; money',
        'level': 'T5',
    },
    {
        'character': '土',
        'reading': 'つち / ど',
        'meaning': 'earth; soil',
        'level': 'T5',
    },
    {
        'character': '山',
        'reading': 'やま / さん',
        'meaning': 'mountain',
        'level': 'T5',
    },
    {
        'character': '川',
        'reading': 'かわ / せん',
        'meaning': 'river',
        'level': 'T5',
    },
    {
        'character': '人',
        'reading': 'ひと / じん',
        'meaning': 'person',
        'level': 'T5',
    },
    {
        'character': '大',
        'reading': 'おおきい / だい',
        'meaning': 'big; large',
        'level': 'T4',
    },
    {
        'character': '小',
        'reading': 'ちいさい / しょう',
        'meaning': 'small',
        'level': 'T4',
    },
    {
        'character': '中',
        'reading': 'なか / ちゅう',
        'meaning': 'middle; inside',
        'level': 'T4',
    },
    {
        'character': '上',
        'reading': 'うえ / じょう',
        'meaning': 'up; above',
        'level': 'T4',
    },
    {
        'character': '下',
        'reading': 'した / か',
        'meaning': 'down; below',
        'level': 'T4',
    },
    {
        'character': '左',
        'reading': 'ひだり / さ',
        'meaning': 'left',
        'level': 'T4',
    },
    {
        'character': '右',
        'reading': 'みぎ / う',
        'meaning': 'right',
        'level': 'T4',
    },
    {
        'character': '本',
        'reading': 'ほん / もと',
        'meaning': 'book; origin',
        'level': 'T4',
    },
    {
        'character': '学',
        'reading': 'まなぶ / がく',
        'meaning': 'study; learning',
        'level': 'T4',
    },
    {
        'character': '生',
        'reading': 'いきる / せい',
        'meaning': 'life; birth',
        'level': 'T4',
    },
    {
        'character': '魚',
        'reading': 'さかな / ぎょ',
        'meaning': 'fish',
        'level': 'T3',
    },
    {
        'character': '肉',
        'reading': 'にく',
        'meaning': 'meat',
        'level': 'T3',
    },
    {
        'character': '卵',
        'reading': 'たまご / らん',
        'meaning': 'egg',
        'level': 'T3',
    },
    {
        'character': '食',
        'reading': 'たべる / しょく',
        'meaning': 'eat; food',
        'level': 'T3',
    },
    {
        'character': '飲',
        'reading': 'のむ / いん',
        'meaning': 'drink',
        'level': 'T3',
    },
    {
        'character': '買',
        'reading': 'かう / ばい',
        'meaning': 'buy',
        'level': 'T3',
    },
    {
        'character': '見',
        'reading': 'みる / けん',
        'meaning': 'see; look',
        'level': 'T3',
    },
    {
        'character': '行',
        'reading': 'いく / こう',
        'meaning': 'go',
        'level': 'T3',
    },
    {
        'character': '来',
        'reading': 'くる / らい',
        'meaning': 'come',
        'level': 'T3',
    },
    {
        'character': '話',
        'reading': 'はなす / わ',
        'meaning': 'talk; story',
        'level': 'T3',
    },
    {
        'character': '時',
        'reading': 'とき / じ',
        'meaning': 'time; hour',
        'level': 'T2',
    },
    {
        'character': '間',
        'reading': 'あいだ / かん',
        'meaning': 'interval; space',
        'level': 'T2',
    },
    {
        'character': '電',
        'reading': 'でん',
        'meaning': 'electricity',
        'level': 'T2',
    },
    {
        'character': '車',
        'reading': 'くるま / しゃ',
        'meaning': 'car; vehicle',
        'level': 'T2',
    },
    {
        'character': '駅',
        'reading': 'えき',
        'meaning': 'station',
        'level': 'T2',
    },
    {
        'character': '会',
        'reading': 'あう / かい',
        'meaning': 'meet; association',
        'level': 'T2',
    },
    {
        'character': '社',
        'reading': 'やしろ / しゃ',
        'meaning': 'company; shrine',
        'level': 'T2',
    },
    {
        'character': '仕',
        'reading': 'つかえる / し',
        'meaning': 'serve; work',
        'level': 'T2',
    },
    {
        'character': '事',
        'reading': 'こと / じ',
        'meaning': 'thing; matter',
        'level': 'T2',
    },
    {
        'character': '国',
        'reading': 'くに / こく',
        'meaning': 'country',
        'level': 'T2',
    },
    {
        'character': '愛',
        'reading': 'あい',
        'meaning': 'love',
        'level': 'T1',
    },
    {
        'character': '夢',
        'reading': 'ゆめ / む',
        'meaning': 'dream',
        'level': 'T1',
    },
    {
        'character': '心',
        'reading': 'こころ / しん',
        'meaning': 'heart; mind',
        'level': 'T1',
    },
    {
        'character': '道',
        'reading': 'みち / どう',
        'meaning': 'road; way',
        'level': 'T1',
    },
    {
        'character': '空',
        'reading': 'そら / くう',
        'meaning': 'sky; empty',
        'level': 'T1',
    },
    {
        'character': '海',
        'reading': 'うみ / かい',
        'meaning': 'sea; ocean',
        'level': 'T1',
    },
    {
        'character': '新',
        'reading': 'あたらしい / しん',
        'meaning': 'new',
        'level': 'T1',
    },
    {
        'character': '古',
        'reading': 'ふるい / こ',
        'meaning': 'old',
        'level': 'T1',
    },
    {
        'character': '高',
        'reading': 'たかい / こう',
        'meaning': 'high; expensive',
        'level': 'T1',
    },
    {
        'character': '長',
        'reading': 'ながい / ちょう',
        'meaning': 'long; leader',
        'level': 'T1',
    },
)
